/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ICallProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICallProxy__factory>;
    getContractFactory(
      name: "IDeBridgeGate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDeBridgeGate__factory>;
    getContractFactory(
      name: "IDeBridgeGateExtended",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDeBridgeGateExtended__factory>;
    getContractFactory(
      name: "Flags",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Flags__factory>;
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "CrossChainCounter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrossChainCounter__factory>;
    getContractFactory(
      name: "CrossChainIncrementor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CrossChainIncrementor__factory>;
    getContractFactory(
      name: "ICrossChainCounter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICrossChainCounter__factory>;

    getContractAt(
      name: "ICallProxy",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICallProxy>;
    getContractAt(
      name: "IDeBridgeGate",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDeBridgeGate>;
    getContractAt(
      name: "IDeBridgeGateExtended",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDeBridgeGateExtended>;
    getContractAt(
      name: "Flags",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Flags>;
    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "CrossChainCounter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrossChainCounter>;
    getContractAt(
      name: "CrossChainIncrementor",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CrossChainIncrementor>;
    getContractAt(
      name: "ICrossChainCounter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICrossChainCounter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
